### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by XemsDoom** [homeslicesolutions/backbone-model-file-upload#20]
Hi Joe,
could you possibly upload this module to npm? I am currently working on a Browserify project and would really like to be able to use most of the JS libs directly from my node_modules folder, instead of manually downloading files from GitHub.

Backbone itself is also on NPM.

**Comment by homeslicesolutions** [comment]
That reminds me that I need to tag this version for git.   The component is on bower.  It seems more fitting there.  Backbone can be on npm cause it can be a utility that is only used for server side.  My plugin however relies on the browser since it deals with file objects so not sure if npm is where it should live.  Again I'm probably naive but happy to learn and hear your thoughts.

**Comment by XemsDoom** [comment]
The most popular js library, jquery, is on npm. Also check [npm's blog](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging) where they explicitly say, that's it is not only for server-side modules.

**Comment by homeslicesolutions** [comment]
It is on NPM now  https://www.npmjs.com/package/backbone-model-file-upload
